name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-latest]
        python-version: ['3.11', '3.12']

    steps:
      - uses: actions/checkout@v4

      # Set up Python environment
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Install build dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "numpy>=2"
          python -m pip install cibuildwheel==2.22.0
          python -m pip install setuptools wheel cython

      # Clean build files (Linux/macOS)
      - name: Clean build files (Linux/macOS)
        if: ${{ runner.os != 'Windows' }}
        run: |
          rm -rf build dist *.egg-info

      # Clean build files (Windows)
      - name: Clean build files (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          # PowerShell script to clean up build files
          if (Test-Path -Path "build") { Remove-Item -Recurse -Force "build" }
          if (Test-Path -Path "dist") { Remove-Item -Recurse -Force "dist" }
          # Correct handling of *.egg-info directories
          Get-ChildItem -Path ".\*.egg-info" -Directory | Remove-Item -Recurse -Force

      # Compile Cython extensions locally (if applicable)
      - name: Compile Cython extensions (setup.py)
        run: python setup.py build_ext --inplace

      # Build the wheels using cibuildwheel
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      # Upload the built wheels as artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
