name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12']  # Explicitly excluding Python 3.13

    steps:
      - uses: actions/checkout@v4

      # Set up Python environment
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Clear cache to avoid previous Python versions being picked up
      - name: Clear pip cache on Linux and macOS
        if: ${{ runner.os != 'Windows' }}
        run: |
          rm -rf ~/.cache/pip

      - name: Clear pip cache on Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          Remove-Item -Recurse -Force $env:USERPROFILE\.cache\pip

      # Install build dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "numpy>=2"
          python -m pip install cibuildwheel==2.22.0
          python -m pip install cython
          python -m pip install setuptools  # Install setuptools

      # Build Cython extensions before wheels
      - name: Build Cython extensions
        run: |
          python setup.py build_ext --inplace  # Compile Cython extensions locally

      # Build the wheels using cibuildwheel
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      # Upload the built wheels as artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
