name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-latest]

    steps:
      - uses: actions/checkout@v4

      # Set up Python environment
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install build dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "numpy>=2"
          python -m pip install cibuildwheel==2.22.0

      # Disable AVX2 in NumPy for Ubuntu to avoid build issues
      - name: Disable AVX2 in NumPy (Ubuntu only)
        if: contains(matrix.os, 'ubuntu')
        run: echo "NPY_DISABLE_CPU_FEATURES=AVX2" >> $GITHUB_ENV

      # Build the wheels using cibuildwheel
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      # Upload the built wheels as artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
